apiVersion: v1
kind: Service
metadata:
  labels:
    app: pages
    tier: service
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: brixton
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pages
    tier: service
  type: NodePort
